#!/usr/bin/env bash
# Installs Nginx web server and configures web content and redirection

# Update packages and install Nginx
apt-get update
apt-get install -y nginx

# Correct the document root and write "Holberton School" to the index.html
echo "Holberton School" > /var/www/html/index.html

# Configure Nginx to handle redirection and serve the updated index file
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://twitter.com/Emmanue17280546;
    }
}
EOF

# Test configuration and restart Nginx
nginx -t && service nginx restart
