#!/usr/bin/env bash
#This script is for debuggin

#Update Nginx configuration to listen on port 80
sed -i 's/^\s*listen\s*\(.*\)/listen 80;/g' /etc/nginx/sites-available/default

#Restart Nginx service
service nginx restart
