#!/usr/bin/env bash
#
#Configure Nginx to listen on port 80 and restart the service

# Ensure that Nginx is set to listen on port 80
if ! grep -q 'listen 80;' /etc/nginx/sites-available/default; then

    sed -i 's/listen .*/listen 80;/' /etc/nginx/sites-available/default
else
    echo "Nginx is already configured to listen on port 80."
fi

# Restart Nginx to apply the changes
service nginx restart
