#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of 4-to_infinity_and_beyond.sh script
pid=$(pgrep -f 4-to_infinity_and_beyond.sh)

# If a PID was found, kill the process
if [[ -n $pid ]]; then
  kill "$pid"
  echo "Process 4-to_infinity_and_beyond ($pid) has been terminated."
else
  echo "Process not found."
fi
