#!/usr/bin/env bash
# Ensure Apache is stopped and disabled
systemctl stop apache2
systemctl disable apache2

# Adjust permissions if necessary
chmod ugo+wrx /etc/nginx/nginx.conf
chmod ugo+wrx /etc/nginx/sites-available/default

# Configure Nginx to run as the nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
systemctl restart nginx

# Verify that Nginx is running as nginx user and listening on port 8080
ps auxff | grep ngin[x]
nc -z 0 8080 ; echo $?
